### ISSUE TITLE
Question about raw data

### ISSUE THREAD

**Issue by 10go-L** [daz/dji-thermal-sdk-docker#1]
Hello, I am interested in your docker to process many images and transform them into temperature data (or any normalization, to be honest). Still, when you convert the images to a raw format, you have to include humidity distance and other info that is supposed to be in the photo's EXIF data. Why is that? Do you know if there is a way to automatically get these values from the picture instead of giving them?

**Comment by daz** [comment]
The flags are all optional. Just leave them blank

**Comment by 10go-L** [comment]
Thanks
