### ISSUE TITLE
M1 Mac installation

### ISSUE THREAD

**Issue by chris-lorenz** [daz/dji-thermal-sdk-docker#3]
Hi, you write, that it's possible to use this on a m1 Mac but how exactly do you build it? What statement do you need for "--platform" and do I have to change any other part of the code when running it while being in the same directory where the Dockerfile is?

Maybe you can help, because I can't find any information about how to install something via a dockerfile when using a Mac.

**Comment by daz** [comment]
Try:

```
git clone https://github.com/daz/dji-thermal-sdk-docker
cd dji-thermal-sdk-docker
docker buildx install
docker buildx build --platform linux/amd64 --load -t djithermal .
```

**Comment by chris-lorenz** [comment]
Thx, it worked. :)

**Comment by daz** [comment]
Awesome 😎
